version: '3.8'

services:
  climbing-soc:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - VIRTUAL_HOST=wucc.containers.uwcs.co.uk
